---
title: "Deliverable #3"
author: "Tony Buranzon"
output:
  html_document:
    df_print: paged
---


Welcome back. As we continue on, in this deliverable I plan to summarize the whole of the project as well as provide some insight as to how this data and our findings can operationalized moving forward. So lets get started. In this deliverable there will be very little if any at all R code. It will focus primarily on theory.

## Review
Looking back, what we have done is gathered data from datasources which describe courses created by users for the game *Super Mario Maker*. We've seen which courses seem to be the most popular based on their difficulty as well as which difficulty of course is most popular to create covered in Deliverable 1. Next in Deliverable 2 we've also built a model to show these attributes and predict the likeness of a given course. Ww then used cross validation in order to determine the confidence in our model. So now the question remains, what do we do with this data.

## Operationalization
Based on the findings we have made, it seems our data would be most useful to those who are making courses and want their creations to become popular. They could use this data to find what seems to be the current trends so they can create courses that match these characteristics. A drawback from this is if a creator solely made tracks that were meant to become popular by using targeted resaetrch such as our findings, is that creator really creating what they truly want to make? 