---
title: "Super Mario Maker" #replace the title with something short and catchy to represent your project
subtitle: "Tony's Data Science Portfolio" #replace blank with your name
output:
  html_document:
    df_print: paged
---

## Abstract

In a world where online gaming is becoming so popular, I want to analyze how users interact in an environment where other users are the creators. Super Mario Maker is a game where anyone can design a course based on the orignal *Super Mario*. This dataset contains information about the different courses users have created and how players have intereacted with them. Addintionally, I chose this dataset because out of the box, this data is very clean and there is a ton of it. With this much data relating to different aspects of the game, it will surely provide an avenue to discover some interesting connections.

### 1. Discovery and Data Preparation

In this deliverable, we will organize, clean and begin to visualize the data by use of some graphs. The original dataset can be found [here](https://www.kaggle.com/leomauro/smmnet#course-meta.csv).

[Deliverable 1](deliverable1.html)
  


### 2. Model Planning and Building

Coming soon...

### 3. Results and Operationalization

Coming soon...

